### ISSUE TITLE
Variable contact number (R0) across study period

### ISSUE THREAD

**Issue by s223102** [reconhub/outbreaker2#88]
Hello, 
I'm new to the software. I have spent some time in the documentation looking for an answer to my question but with no succes. 

I have indications from other analyses of my data that the contact number (R0) is varying across the study period. 
Is there a way to include this information in the outbreak analysis?

Thanks in advance, 
Esben

**Comment by finlaycampbell** [comment]
Hi Esben, 

Thanks for getting in touch and sorry for the slow reply! I'm not quite sure I understand the question; do you mean you have prior knowledge that the basic reproduction number is changing over the course of the outbreak? 

outbreaker implicitly estimates the *effective* reproduction number over time by reconstructing the transmission network, which can be extracted by counting the number of infections caused by each case and relating that to the time of infection of that primary case. In that sense the reproduction number is inferred, and not used as an input. 

If you mean you would like to incorporate this information in the form of a prior distribution, unfortunately this is not possible in outbreaker and we do not explicitly model the reproduction number.

I'm happy to answer any more questions, but please direct these to finlaycampbell93@gmail.com as this forum is meant for technical issues, not methods questions. Thanks :)
